# Generated by Django 5.1.5 on 2025-02-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_companyprofile_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyprofile',
            old_name='contact_email',
            new_name='contact_info',
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Skilles'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('recruiter', 'Recruiter')], default='jobseeker', max_length=10, verbose_name='User Role'),
        ),
    ]
