# Generated by Django 5.1.5 on 2025-02-14 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_contact_email_companyprofile_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='users.userprofile', verbose_name='User Profile'),
        ),
    ]
