# Generated by Django 5.1.5 on 2025-02-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_companyprofile_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('recruiter', 'Recruiter')], max_length=10, verbose_name='User Role'),
        ),
    ]
