# Generated by Django 5.1.5 on 2025-02-19 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.companyprofile', verbose_name='Company'),
        ),
    ]
