# Generated by Django 5.1.5 on 2025-02-27 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_jobseeker_experience_jobseeker_job_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='experience',
            field=models.PositiveIntegerField(blank=True, help_text='Enter experience in years', null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='skills',
            field=models.JSONField(blank=True, default=list, verbose_name='Skills'),
        ),
        migrations.AlterField(
            model_name='jobseeker',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to='users.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruiters', to='users.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to='users.userprofile', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
