# Generated by Django 5.1.5 on 2025-02-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Job Title')),
                ('description', models.TextField(verbose_name='Job Description')),
                ('location', models.CharField(max_length=100, verbose_name='Job Location')),
                ('required_skills', models.TextField(help_text='Comma-seprated skills', verbose_name='Required Skills')),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=20, verbose_name='JOb type')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum Salary')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='Job Posted Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Jobs', to='users.companyprofile', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, verbose_name='Application Status')),
                ('applied_at', models.DateField(auto_now_add=True, verbose_name='Job Application Date')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.jobseeker', verbose_name='Job Seeker Name')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
