# Generated by Django 5.1.5 on 2025-02-14 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('users', '0003_rename_contact_email_companyprofile_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.companyprofile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(default=list, verbose_name='Required Skills'),
        ),
    ]
