# Generated by Django 5.1.5 on 2025-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_posted_by_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(default=list, verbose_name='Required Skills'),
        ),
    ]
